version: '3'
services:
  web:
    build: .
    ports:
     - "4000:80"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
